### ISSUE TITLE
Mensajes de error

### ISSUE THREAD

**Issue by sebastianmarines** [Tall-Programacion-FIME/backend#35]
Checa que todos los errores que vienen en el backend, estén en español, y trata de no tener puntos al final de las oraciones

**Comment by sebastianmarines** [comment]
@HectorMtz22

**Comment by HectorMtz22** [comment]
Si quieres lo hago yo, para estar como colaborador en el backend 🥺
@sebastianmarines

**Comment by sebastianmarines** [comment]
Ok, faltan pocos y ya modifique algunos.
Vamos a ver que pasa si hay conflictos entre nuestros pull requests.
